version: "3.8"
services: 
  mongodb:
    image: 'mongo'
    volumes:
      - data:/data/db
        #enviroenment:
      #     MAX_INITDB_ROOT_USERNAME: max
      #MAX_INITDB_ROOT_USERNAME=max
      #MAX_INITDB_ROOT_PASSWORD=secret
    env_file:
      - ./env/mongo.env
    container_name: mongodb_container

  backend:
    build: ./backend
    ports:
      - '80:80'
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      ./env/backend.env
    depends_on:
      - mongodb
    container_name: backend_container

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend
    container_name: frontend_container

volumes:
  data:
  logs:

